/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sanjeevaniapp.gui;


import Sanjeevaniapp.Dao.DoctorsDao;
import Sanjeevaniapp.Dao.PatientDao;
import Sanjeevaniapp.pojo.PatientPojo;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class AddPatientFrame extends javax.swing.JFrame {
      List<String>doctorIds;
      String patientId;
      java.sql.Date dt;
      private PatientPojo patient;
      private static int OTP=1000+(int)(Math.random()*999);
   public AddPatientFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadDoctorIds();
        getNewPatientId();
       // validateInputs();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel102 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtPatientId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtOPD = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtMoNo = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jcDoctorId = new javax.swing.JComboBox<>();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jcStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcGender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1160, 760));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 78, 430, -1));

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 153, 153));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, -1, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 308, 1160, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 540, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Sanjeevani Application");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 440, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanjeevaniapp/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1160, 390));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanjeevaniapp/icons/images (2).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 250, 330));

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 153, 153));
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 120, -1));

        btnAddPatient.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddPatient.setForeground(new java.awt.Color(0, 153, 153));
        btnAddPatient.setText("REGISTER");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 660, 230, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 90, -1));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel102.setText("Add Patient Frame");
        jPanel1.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 40));

        jPanel11.setBackground(new java.awt.Color(170, 210, 210));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPatientId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 190, 230, -1));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 244, 230, -1));

        txtCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        jPanel11.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 298, 230, -1));

        txtOPD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtOPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 76, 230, -1));

        txtLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 130, 227, -1));

        txtMoNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtMoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 298, 227, -1));

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 244, 227, -1));

        txtFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel11.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 76, 227, -1));

        jcDoctorId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcDoctorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDoctorIdActionPerformed(evt);
            }
        });
        jPanel11.add(jcDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 130, 230, -1));

        jLabel103.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel103.setText("Patient's Details ");
        jPanel11.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 41));

        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel104.setText("First Name");
        jPanel11.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 77, -1, -1));

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel105.setText("Last Name");
        jPanel11.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 131, -1, -1));

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel106.setText("Date ");
        jPanel11.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 245, -1, -1));

        jLabel107.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel107.setText("Phone No.");
        jPanel11.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 299, -1, -1));

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel108.setText("Marital Status");
        jPanel11.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 354, -1, 35));

        jLabel109.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel109.setText("OPD");
        jPanel11.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 77, -1, -1));

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel124.setText("DoctorId");
        jPanel11.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 131, -1, -1));

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel125.setText("Patient Id");
        jPanel11.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 191, -1, -1));

        jLabel126.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel126.setText("Age");
        jPanel11.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 245, -1, -1));

        jLabel127.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel127.setText("City");
        jPanel11.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 299, -1, -1));

        jLabel128.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel128.setText("Address");
        jPanel11.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 354, -1, 35));

        jcStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Unmarried" }));
        jPanel11.add(jcStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 354, 227, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Gender");
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 191, 105, -1));

        jcGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel11.add(jcGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 190, 227, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 354, 230, 50));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 890, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoginFrame lf = new LoginFrame ();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed

        System.out.println(dt+"+"+doctorIds);
        
        if(!validateInputs()){
            return;
        }
        patient.setOtp(OTP);
        patient.setAptStatus("REQUEST");
        patient.setOpd(txtOPD.getText().trim());
        VerifyOTPFrame verify=new VerifyOTPFrame(patient);
        this.dispose();
        verify.setVisible(true);
     
        
    
        
       


    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      ReceptionistOptionFrame RO = new ReceptionistOptionFrame();
      RO.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed

    }//GEN-LAST:event_txtCityActionPerformed

    private void jcDoctorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDoctorIdActionPerformed
    
    }//GEN-LAST:event_jcDoctorIdActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcDoctorId;
    private javax.swing.JComboBox<String> jcGender;
    private javax.swing.JComboBox<String> jcStatus;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMoNo;
    private javax.swing.JTextField txtOPD;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables

  private void loadDoctorIds() {
        try{
            doctorIds=DoctorsDao.getAllDoctorId();
            for(String docId:doctorIds){
                jcDoctorId.addItem(docId);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in DB:"+ex);
            System.out.println("Error in DB");
            ex.printStackTrace();
        }
    }

    private void getNewPatientId() {
        try{
            patientId=PatientDao.getNewPatientId();
            txtPatientId.setText(patientId);
            
            Date today=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-yyyy");
            String dateStr=sdf.format(today);
            txtDate.setText(dateStr);
            java.util.Date d1=sdf.parse(dateStr);
            long ms=d1.getTime();
            dt=new java.sql.Date(ms);
            
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in DB:"+ex);
            System.out.println("Error in DB");
            ex.printStackTrace();
        }
        catch(ParseException ex){
            JOptionPane.showMessageDialog(null,"Error in date conversion:"+ex);
            ex.printStackTrace();
        }
    }
   private boolean validateInputs(){
       patient=new PatientPojo();
       patient.setPatientId(txtPatientId.getText().trim());
       //patient.setAge(txtAge.getText().trim());
       patient.setCity(txtCity.getText().trim());
       patient.setAddress(txtAddress.getText().trim());
       patient.setFirstName(txtFirstName.getText().trim());
       patient.setLastName(txtLastName.getText().trim());
       patient.setGender(jcGender.getSelectedItem().toString());
       patient.setMarriedStatus(jcStatus.getSelectedItem().toString());
       patient.setDoctorId(jcDoctorId.getSelectedItem().toString());
       patient.setDate(dt);
       patient.setMno(txtMoNo.getText().trim());
       if(patient.getCity().isEmpty()||patient.getFirstName().isEmpty()||patient.getLastName().isEmpty()||patient.getAddress().isEmpty())
       {
           JOptionPane.showMessageDialog(null,"Please fill all the fields");
           return false;
           
       }  
           
    try{
           patient.setAge(Integer.parseInt(txtAge.getText().trim().toString()));
           
       }catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(null,"Invalid age"+ex);
          return false;
       }
    if(!isContactNoValid()){
        JOptionPane.showMessageDialog(null,"Invalid Mobile no");
        return false;
    }
    return true;
   }
   private boolean isContactNoValid(){
      char[]mob=patient.getMno().toCharArray();
      for(char ch:mob){
          if(Character.isDigit(ch)==false)
              return false;
      }
      if(patient.getMno().length()==10)
            return true;
      return false;
  }
}
